export enum MessageType {
  MATCH_REQUEST = 'MATCH_REQUEST',
  MATCH_REQUEST_QUEUED = 'MATCH_REQUEST_QUEUED',
  MATCH_FOUND = 'MATCH_FOUND',
  MATCH_CANCEL = 'MATCH_CANCEL',
  MATCH_CANCELLED = 'MATCH_CANCELLED',
  MATCH_REQUEST_FAILED = 'MATCH_REQUEST_FAILED',
}
